MvcNetCoreUtilidades/Models/ErrorViewModel.cs
namespace MvcNetCoreUtilidades.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcNetCoreUtilidades/Controllers/CifradosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreUtilidades.Helpers;

namespace MvcNetCoreUtilidades.Controllers
{
    public class CifradosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CifradoBasico()
        {
            return View();
        }

        public IActionResult CifradoEficiente()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CifradoEficiente(string contenido, string resultado, string accion)
        {
            if (accion.ToLower() == "cifrar")
            {
                string response = HelperCriptography.EncriptarTxtBasicoSalt(contenido, false);
                ViewData["Cifrado"] = response;
                ViewData["Salt"] = HelperCriptography.Salt;
            }
            else if (accion.ToLower() == "comparar")
            {
                string response = HelperCriptography.EncriptarTxtBasicoSalt(contenido, true);

                if (response != resultado)
                {
                    ViewData["Comparacion"] = "Los datos no coinciden :(";
                }
                else
                {
                    ViewData["Comparacion"] = "Los datos coinciden, bieeeeeen";
                }
            }

            return View();
        }

        [HttpPost]
        public IActionResult CifradoBasico(string contenido, string resultado, string accion)
        {
            //ciframos el contenido
            string response = HelperCriptography.EncriptarTxtBasico(contenido);

            if (accion.ToLower() == "cifrar")
            {
                ViewData["Cifrado"] = response;
            }
            else if (accion.ToLower() == "comparar")
            {
                //si se quiere comprarar
                //nos envia el txt en el resultado
                if (response != resultado)
                {
                    ViewData["Comparacion"] = "Los datos no coinciden :(";
                }
                else
                {
                    ViewData["Comparacion"] = "Los datos coinciden, bieeeeeen";
                }
            }
                return View();
        }
    }
}

MvcNetCoreUtilidades/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreUtilidades.Models;

namespace MvcNetCoreUtilidades.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcNetCoreUtilidades/Controllers/MailsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Net.Mail;

namespace MvcNetCoreUtilidades.Controllers
{
    public class MailsController : Controller
    {
        private IConfiguration conf;

        public MailsController(IConfiguration conf)
        {
            this.conf = conf;
        }

        public IActionResult SendMail()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SendMail(string to, string asunto, string mensaje)
        {
            string user = conf.GetValue<string>("MailSettings:Credentials:User");

            //objeto para la informacio del mail
            MailMessage mail = new MailMessage();
            mail.From = new MailAddress(user);
            mail.To.Add(to);
            mail.Subject = asunto;
            mail.Body = mensaje;
            //se puede interpretar un html con 
            mail.IsBodyHtml = true;
            //se le puede poner prioridad
            mail.Priority = MailPriority.Normal;

            //recuperamos los datos para el obj que manda el propio mail
            string password = conf.GetValue<string>("MailSettings:Credentials:Password");
            string host = conf.GetValue<string>("MailSettings:Server:Host");
            int port = conf.GetValue<int>("MailSettings:Server:Port");
            bool ssl = conf.GetValue<bool>("MailSettings:Server:Ssl");
            bool defaultCredentials = conf.GetValue<bool>("MailSettings:Server:DefaultCredentials");

            SmtpClient client = new SmtpClient();
            client.Host = host;
            client.Port = port;
            client.EnableSsl = ssl;
            client.UseDefaultCredentials = defaultCredentials;

            //credenciales para el mail
            NetworkCredential cred = new NetworkCredential(user, password);
            client.Credentials = cred;
            await client.SendMailAsync(mail);

            ViewData["Mensaje"] = "Email mandado correctamente !!";

            return View();
        }
    }
}

MvcNetCoreUtilidades/Views/Cifrados/CifradoBasico.cshtml
<h1>Cifrado basico</h1>

<form method="post">
    <label>Password</label>
    <br/>
    <input type="text" name="contenido"/>
    <hr/>
    <label>Resultado cifrado: </label>
    <br/>
    <textarea rows="5" name="resultado">@ViewData["Cifrado"]</textarea>
    <hr/>
    <button name="accion" value="cifrar">Cifrar</button>
    <button name="accion" value="comparar">Comparar</button>
</form>

<h2>@ViewData["Comparacion"]</h2>

MvcNetCoreUtilidades/Views/Cifrados/CifradoEficiente.cshtml
<h1>Cifrado eficiente</h1>

<form method="post">
    <label>Password</label>
    <br />
    <input type="text" name="contenido" />
    <hr />
    <label>Resultado cifrado: </label>
    <br />
    <textarea rows="5" name="resultado">@ViewData["Cifrado"]</textarea>
    <hr />
    <button name="accion" value="cifrar">Cifrar</button>
    <button name="accion" value="comparar">Comparar</button>
</form>

<h2>@ViewData["Salt"]</h2>
<h2>@ViewData["Comparacion"]</h2>   

MvcNetCoreUtilidades/Views/Cifrados/Index.cshtml
<h1>Encriptacion</h1>

<ul>
    <li>
        <a asp-controller="Cifrados" asp-action="CifradoBasico">Cifrado Basico</a>
    </li>
    <li>
        <a asp-controller="Cifrados" asp-action="CifradoEficiente">Cifrado Eficiente</a>
    </li>
</ul>

MvcNetCoreUtilidades/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcNetCoreUtilidades/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcNetCoreUtilidades</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcNetCoreUtilidades.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcNetCoreUtilidades</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mails" asp-action="SendMail">Mail</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cifrados" asp-action="Index">Encriptacion</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - MvcNetCoreUtilidades - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcNetCoreUtilidades/Views/UploadFiles/SubirFile.cshtml
<h1>Subir ficheros Net Core</h1>